---
- name: Generate self-signed SSL certificate
  ansible.builtin.openssl_certificate:
    path: /etc/ssl/certs/{{ server_name }}.crt
    privatekey_path: /etc/ssl/private/{{ server_name }}.key
    owner: root
    group: root
    mode: '0644'
  register: ssl_certificate

- name: Copy SSL certificate to remote hosts
  ansible.builtin.copy:
    src: /etc/ssl/certs/{{ server_name }}.crt
    dest: /etc/ssl/certs/{{ server_name }}.crt
    owner: root
    group: root
    mode: '0644'
  run_once: true

- name: Copy SSL private key to remote hosts
  ansible.builtin.copy:
    src: /etc/ssl/private/{{ server_name }}.key
    dest: /etc/ssl/private/{{ server_name }}.key
    owner: root
    group: root
    mode: '0600'
  run_once: true

- name: Enable SSL module in Apache
  ansible.builtin.shell: a2enmod ssl
  become: true

- name: Update Apache VirtualHost configuration with SSL
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/app.conf
    regexp: 'VirtualHost \*:80'
    replace: 'VirtualHost \*:443'
  become: true

- name: Update Apache VirtualHost configuration with SSL directives
  ansible.builtin.blockinfile:
    path: /etc/apache2/sites-available/app.conf
    block: |
      SSLEngine on
      SSLCertificateFile /etc/ssl/certs/{{ server_name }}.crt
      SSLCertificateKeyFile /etc/ssl/private/{{ server_name }}.key
  become: true

- name: Restart Apache service
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
