---
- name: Install PHP, Python, Git, Pip
  hosts: web
  become: true

  tasks:
    - name: Install apache2
      apt:
        name: apache
        state: present

    - name: Install PHP
      apt:
        name: php8.1
        state: present

    - name: Install libapache2-mod-php8.1
      apt:
        name: libapache2-mod-php8.1
        state: present

    - name: Install Python
      apt:
        name: python
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Pip
      apt:
        name: python-pip
        state: present
