---
- name: Install PHP, Python, Git, Pip
  hosts: web
  become: true

  tasks:
    - name: Install apache2
      apt:
        update_cache: true
        name: apache2
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Pip
      apt:
        name: pip
<<<<<<< HEAD
        state: present
=======
        state: present
>>>>>>> d16e5d05567f5dc4f17f902b239841978f669f6f
