---
- name: Install PHP, Python, Git, Pip
  hosts: web
  become: true

  tasks:
    - name: Install apache2
      apt:
        update_cache: true
        name: apache2
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Pip
      apt:
        name: pip
        state: present
