---
- name: Install and configure MySQL
  hosts: sql
  become: true
  vars_files:
    - vars.yml
 
  tasks:
    - name: Mise à jour du cache des paquets 1
      apt:
        update_cache: yes

    - name: Installation de gpg
      apt:
        name: gnupg
        state: present

    - name: Import MySQL APT GPG key
      apt_key:
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/A4A9406876FCBD3C456770C88C718D3B5072E1F5
        state: present


    - name: Add MySQL APT repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/ buster mysql-8.0"
        state: present

    - name: Set debconf selection for MySQL Server
      debconf:
        name: mysql-apt-config
        question: "mysql-apt-config/repo-distro"
        value: "mysql"
        vtype: select
      become: yes

    - name: Install MySQL Server package
      apt:
        name: mysql-server
        state: present

    - name: Mise à jour du cache apt
      apt:
        update_cache: yes


    - name: Start MySQL 
      service:
        name: mysql
        state: started
        enabled: true

    
    - name: Install Pip3
      apt:
        name: python3-pip
        state: present
    - name: Install libmysql-dev
      apt:
        name: libmysqlclient-dev
        state: present

    - name: Install requirements
      pip: 
        name: 
          - tqdm
          - numpy
          - pandas
          - openpyxl
          - mysql-connector-python
          - PyMySQL
          - mysqlclient
        state: present

    - name: Secure MySQL installation
      become: true
      vars_prompt:
        - name: mysql_root_password
          prompt: "Enter MySQL root password"
          private: yes
      environment:
        MYSQL_PWD: "{{ mysql_root_password }}"
      command: mysql_secure_installation --use-default --password="{{ mysql_root_password }}"



    - name: Créer MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Créer MySQL databases
      mysql_db:
        name: cis_nord_warwait
        state: present

    - name: Créer 2ème MySQL database
      mysql_db:
        name: skillmatrix
        state: present


    - name: Install Git
      apt:
        name: git
        state: present

    - name: Créer un dossier s'il n'existe pas déjà
      file:
        path: /home/admin/app
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/simonLongatte/Projectwarwaitcap.git
        dest: /home/admin/app
        version: development
        force: yes

    

    - name: Mettre à jour les valeurs d'utilisateur et de mot de passe dans withoutGr.py
      template:
        src: withoutGr.py.j2
        dest: /home/admin/app/Projet/AppPython/withoutGr.py
      
    - name: Init Wait Room
      command: python3 Projet/AppPython/withoutGr.py -W '/home/admin/Wait_Room_2023.xlsx'
      args:
        chdir: /home/admin/app

    - name: Init Matrice
      command: python3 Projet/AppPython/withoutGr.py -MC '/home/admin/Matrice_des_competences.xlsx'
      args:
        chdir: /home/admin/app

- name: Dernières modifications apache2
  hosts: web
  become: true
  tasks:
    - name: owner for /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: permissions for /var/www/html/script
      file:
        path: /var/www/html/script
        recurse: yes
        mode: "a+x"

    - name: Modify Apache configuration
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^<Directory /var/www/>'
        line: '<Directory /var/www/html/>'

    - name: Install MySQL Client on Debian/Ubuntu
      apt:
        name: default-mysql-client
        state: present


    - name: restart apache2
      service:
        name: apache2
        state: restarted