mysql_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
mysql_user: "{{ lookup('env', 'MYSQL_USER') }}"
mysql_password: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
debian_name: bullseye
mysql_version: 8.0
