mysql_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
mysql_user: "{{ lookup('env', 'MYSQL_USER') }}"
mysql_password: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
debian_name: bullseye
mysql_version: 8.0
mysql_databases: 
  - name: cis_nord_warwait
  - name: skillmatrix
mysql_users: 
  - name: "{{ lookup('env', 'MYSQL_USER') }}"
    password: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
    priv: "*.*:ALL"

ssl_cert_file: "mon_certificat.crt"
ssl_key_file: "ma_cle_privee.key"

